load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "search",
    hdrs = [
        "find_best_move.h",
        "statistic.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//bitboard"],
)
