load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "hardware",
    hdrs = [
        "population_count.h",
        "trailing_zeros_count.h",
    ],
    visibility = ["//visibility:public"],
)
