load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lookup_table",
    srcs = [
        "knight.h",
        "pawn.h",
        "utilities.h",
    ],
    hdrs = [
        "knight.h",
        "pawn.h",
        "utilities.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//hardware"],
)
