load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lookup_table",
    hdrs = [
        "bishop.h",
        "king.h",
        "knight.h",
        "pawn.h",
        "ray.h",
        "rook.h",
        "utilities.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//hardware"],
)
