load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = ["trailing_zeros_count_unit_tests.cpp"],
    deps = [
        "//hardware",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
