load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "evaluate",
    hdrs = [
        "evaluate.h",
        "evaluation.h",
        "player.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bitboard",
        "//hardware",
    ],
)
