load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test",
    srcs = ["bubikopf_unit_test.cpp"],
    deps = [
        "//play:bubikopf",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
